site_name: Programación Didáctica del CE en Ciberseguridad
theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - header.autohide

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
# Configuración de ejemplo, no se aplicará mientras que no se elimine este plugin de los .yml de cada proyecto
plugins:
  - search:
      lang: es
  - with-pdf:
      author: Equipo educativo de ciberseguridad del IES Rafael Alberti
      copyright: CC BY-SA 4.0
      debug_html: true
      cover: true
      toc_title: "Índice"
      cover_title: Programación Didáctica
      cover_subtitle: Curso de especialización en ciberffffffffffffffffffffff ffffffffffffffffff 
      cover_logo: assets/portada-ies-rafael-alberti.svg
      cover_logo2: assets/portada.png

      custom_template_path: docs/templates
      output_path: ../../tetst.pdf
extra:
  course_year: "Curso 2024 / 2025"
  department: "Departamento de informática"
  institution: "IES Rafael Alberti, Cádiz"

# Page tree
nav:
  - Home: PD.md

copyright: Contenido generado por el equipo educativo de ciberseguridad del IES Rafael Alberti
