name: Build PDF with MkDocs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip 
        pip3 install mkdocs mkdocs-material==9.5.42 mkdocs-with-pdf

    - name: Run build-pdf.sh
      run: |
        chmod +x build-pdf.sh
        ./build-pdf.sh
  
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Build PDF and commit to repository"

    - name: Push changes to repository
      run: git push origin main -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
