name: Build PDF with MkDocs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
        pip install wheel mkdocs mkdocs-material mkdocs-with-pdf django-weasyprint
    - name: Run build-pdf.sh
      run: |
        chmod +x build-pdf.sh
        ./build-pdf.sh
  
    - name: Push changes to repository
      run: git push origin HEAD:main
